#!/usr/bin/env bash
#bash script that creates RSA key pairs

# parameters for the SSH key
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Creating the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f ~/.ssh/$KEY_NAME -N "$PASSPHRASE"
